name: Hello world workflow
on:
  push:
    branches: 
      - master:
  pull_request:
    branches:
      - master:
  workflow_dispatch:

jobs:
  hello:
    run-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: hello world
        run: echo "Hello world"
        shell: bash 

  goodbye:
    run-on: ubuntu-latest
    steps:
      - name: goodbye world 
        run: echo "Goodbye world" 
        shell: bash
